CREATE TABLE AUTOR (
	"ID_AUTOR" NUMBER(3,0) NOT NULL, 
	"NOME" VARCHAR2(200 BYTE) NOT NULL, 
		CONSTRAINT "AUTOR_PK" PRIMARY KEY ("ID_AUTOR")
);


CREATE TABLE EDITORA (
	"ID_EDITORA" NUMBER(3,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		CONSTRAINT "EDITORA_PK" PRIMARY KEY ("ID_EDITORA")
);


CREATE TABLE GENERO (
	"ID_GENERO" NUMBER(3,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		CONSTRAINT "GENERO_PK" PRIMARY KEY ("ID_GENERO")
); 

CREATE TABLE SUPORTE (
	"ID_SUPORTE" NUMBER(3,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		CONSTRAINT "SUPORTE_PK" PRIMARY KEY ("ID_SUPORTE")
);

CREATE TABLE TITULO (
    ID_TITULO INT NOT NULL PRIMARY KEY,
    TITULO VARCHAR(45) NOT NULL,
    PRECO FLOAT NOT NULL,
    DATA_COMPRA DATE NOT NULL,
    ID_EDITORA INTEGER NOT NULL,
    ID_SUPORTE INTEGER NOT NULL,
    ID_GENERO INTEGER NOT NULL,
    ID_AUTOR INTEGER NOT NULL,
    FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA(ID_EDITORA),
    FOREIGN KEY (ID_SUPORTE) REFERENCES SUPORTE(ID_SUPORTE),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
);


CREATE TABLE MUSICA (
	"ID_MUSICA" NUMBER(5,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID_AUTOR" NUMBER(3,0) NOT NULL ENABLE, 
	"ID_TITULO" NUMBER(5,0) NOT NULL ENABLE, 
		CONSTRAINT "MUSICA_PK" PRIMARY KEY ("ID_MUSICA"), 
		CONSTRAINT "MUSICA_FK1" FOREIGN KEY ("ID_AUTOR")
			REFERENCES AUTOR ("ID_AUTOR") ENABLE, 
		CONSTRAINT "MUSICA_FK2" FOREIGN KEY ("ID_TITULO")
			REFERENCES TITULO ("ID_TITULO") ENABLE
   );
   
 
CREATE TABLE REVIEW (
	"ID_REVIEW" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_TITULO" NUMBER(5,0) NOT NULL ENABLE, 
	"DTA_REVIEW" DATE NOT NULL ENABLE, 
	"CONTEUDO" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
		CONSTRAINT "REVIEW_PK" PRIMARY KEY ("ID_REVIEW"),
		CONSTRAINT "REVIEW_FK1" FOREIGN KEY ("ID_TITULO")
			REFERENCES TITULO ("ID_TITULO") ENABLE
);


